default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_action_cable_sample_dev

test:
  <<: *default
  database: rails_action_cable_sample_test

production:
  <<: *default
  database: rails_action_cable_sample_prod
